# -*- coding: utf-8 -*-
"""Assignment 1 part 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rIS4_zUhy-tFvCVDaGl3e-qtyahL_3WL
"""

import pandas as pd
import sqlite3

df = pd.read_csv('buddymove_holidayiq.csv')
df.shape

df.head()

df.isnull().sum()

conn = sqlite3.connect('buddymove_holidayiq.sqlite')

cur = conn.cursor()

conn_new = sqlite3.connect('buddymove_holidayiq.sqlite')

c = sqlite3.connect('buddymove_holidayiq.sqlite')
cursor = c.cursor

select_statement = "SELECT * FROM User Id"
cursor.execute(select_statement)

results = c.cursor.fetchcall()

print(results)

df_2 = df.to_sql('review', conn_new)

conn.cursor.execute("SELECT * FROM User Id").fetchall()

